version: "3.8"
services:

    bd-xe:
        image: oracle/database:18.4.0-xe
        ports:
            - "1521:1521"
            - "5500:5500"
        volumes:
            - ./data:/opt/oracle/oradata
        environment:
            - ORACLE_PWD=password

        restart: unless-stopped